In [1]:
import numpy as np

In [2]:
import numpy as np

# Creating a 1D array from a list
array_from_list = np.array([1, 2, 3, 4, 5])

# Creating a 2D matrix from a list of lists
matrix_from_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array from list:")
print(array_from_list)

print("\nMatrix from list:")
print(matrix_from_list)


Array from list:
[1 2 3 4 5]

Matrix from list:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np

# Creating a 1D array with zeros
zeros_array = np.zeros(5)

# Creating a 2D matrix with zeros
zeros_matrix = np.zeros((3, 4))

print("Zeros array:")
print(zeros_array)

print("\nZeros matrix:")
print(zeros_matrix)


Zeros array:
[0. 0. 0. 0. 0.]

Zeros matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
import numpy as np

# Creating a 1D array with ones
ones_array = np.ones(4)

# Creating a 2D matrix with ones
ones_matrix = np.ones((2, 3))

print("Ones array:")
print(ones_array)

print("\nOnes matrix:")
print(ones_matrix)


Ones array:
[1. 1. 1. 1.]

Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import numpy as np

# Creating a 1D array using arange
arange_array = np.arange(0, 10, 2)  # start, stop, step

print("Arange array:")
print(arange_array)


Arange array:
[0 2 4 6 8]


In [6]:
import numpy as np

# Define the matrices A and B
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Addition (A + B)
result_addition = matrix_a + matrix_b

# Subtraction (A - B)
result_subtraction = matrix_a - matrix_b

# Multiplication (A * B)
result_multiplication = np.dot(matrix_a, matrix_b)

# Division (A / B)
result_division = np.divide(matrix_a, matrix_b)

# Matrix Multiplication (A @ B)
result_matrix_multiplication = np.matmul(matrix_a, matrix_b)

# Print the results
print("Addition (A + B):\n", result_addition)
print("\nSubtraction (A - B):\n", result_subtraction)
print("\nMultiplication (A * B):\n", result_multiplication)
print("\nDivision (A / B):\n", result_division)
print("\nMatrix Multiplication (A @ B):\n", result_matrix_multiplication)


Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication (A * B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Division (A / B):
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Matrix Multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [7]:
import numpy as np

# Matrix from list
matrix_from_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reshaping to (1, 9) and (9, 1)
reshaped_1_9 = matrix_from_list.reshape(1, 9)
reshaped_9_1 = matrix_from_list.reshape(9, 1)

# Transposing
transposed_matrix = matrix_from_list.T

print("Original Matrix:")
print(matrix_from_list)

print("\nReshaped to (1, 9):")
print(reshaped_1_9)

print("\nReshaped to (9, 1):")
print(reshaped_9_1)

print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped to (1, 9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped to (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
roll = []
score = []
file = open("data6.txt", "r")

for line in file.readlines():
    roll.append(line.split("\t")[0])
    score.append(line.split("\t")[1].rstrip("\n"))

In [11]:
for x, i in enumerate(score):
    if i == '5':
        print(x, i)

2 5
5 5
9 5
12 5
16 5
20 5
23 5
27 5
29 5
33 5
39 5
41 5
45 5
48 5
58 5
59 5
60 5
67 5
75 5
82 5
89 5
