## Name-Abhishek Kumar
## Roll-2105598

In [2]:
import numpy as np

In [3]:
#Create NumPy arrays and matrices with following methods
a=[1,2,3,4]
na=np.array(a)

print(a)
print(na)

[1, 2, 3, 4]
[1 2 3 4]


In [4]:
type(na)

numpy.ndarray

In [7]:
# list

list=[[1,2,3],[4,5,6]]
na2=np.array(list)
print(na2)

[[1 2 3]
 [4 5 6]]


In [11]:
#assign np array with all 0
na=np.zeros((2,3))
print(na)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
na=np.zeros((3))
print(na)

[0. 0. 0.]


In [13]:
#assign np array with all ones(1)
na=np.ones((2,3))
print(na)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
na=np.ones(3)
print(na)

[1. 1. 1.]


In [22]:
#Perform mathematical operations on NumPy matrices (addition, subtraction,multiplication, division, matrix maltiplication)
a1=[[1,3,3],[5,4,8],[9,7,2]]
a2=[[1,2,3],[4,5,9],[9,2,7]]
arr1=np.array(a1)
arr2=np.array(a2)

print('Sum')
print(arr1+arr2)
print('Sub')
print(arr1-arr2)
print('Mul')
print(arr1*arr2) # n*m m*p -col of first array must equal to row of 2nd array
print('Div')
print(arr1/arr2)

Sum
[[ 2  5  6]
 [ 9  9 17]
 [18  9  9]]
Sub
[[ 0  1  0]
 [ 1 -1 -1]
 [ 0  5 -5]]
Mul
[[ 1  6  9]
 [20 20 72]
 [81 14 14]]
Div
[[1.         1.5        1.        ]
 [1.25       0.8        0.88888889]
 [1.         3.5        0.28571429]]


In [23]:
print(np.matmul(arr1,arr2))

[[ 40  23  51]
 [ 93  46 107]
 [ 55  57 104]]


In [26]:
arr=np.array([1,2,3,10,5,3])

print(np.amin(arr))
print(np.amax(arr))
print(np.argmax(arr))

1
10
3


In [39]:
arr=np.array([[1,2,3],[4,5,6],[7,8,10]])
print(arr.reshape(9,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]]


In [38]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [62]:
#assigment
roll=[]
score=[]

file=open('data.txt','r')
for line in file.readlines():
    roll.append(line.split('\t')[0])
    score.append(line.split('\t')[1].rstrip('\n'))

print(roll)
print(score)

['Roll', '2005011', '2005058', '2005076', '2005119', '2005150', '2005161', '2005168', '2005178', '2005179', '2005198', '2005270', '2005278', '2005288', '2005289', '2005312', '2005324', '2005326', '2005332', '2005343', '2005407', '2005439', '2005444', '2005473', '2005521', '2005548', '2005554', '2005574', '2005578', '2005585', '2005590', '2005597', '2005598', '2005601', '2005603', '2005608', '2005628', '2005631', '2005645', '2005704', '2005718', '2005721', '2005849', '2005904', '2005909', '2005929', '2005955', '2005979', '20051001', '20051023', '20051042', '20051049', '20051105', '20051122', '20051143', '20051164', '20051167', '20051174', '20051182', '20051254', '20051329', '20051351', '20051359', '20051362', '20051388', '20051397', '20051420', '20051433', '20051467', '20051473', '20051510', '20051552', '20051562', '20051614', '20051633', '20051805', '20051855', '20051866', '20051868', '20051872', '20051888', '20051903', '20051915', '20051962', '20051981', '21053002', '21053015', '21053

In [63]:
roll_numbers = np.array(roll)
marks = np.array(score)

# a. Find the serial number of the students who have got 5 marks
students_with_5_marks = roll_numbers[marks == '5']
print("Serial numbers of students who got 5 marks:", students_with_5_marks)

Serial numbers of students who got 5 marks: ['2005058' '2005150' '2005179' '2005278' '2005324' '2005407' '2005473'
 '2005574' '2005585' '2005601' '2005704' '2005721' '2005929' '20051001'
 '20051182' '20051254' '20051329' '20051433' '20051805' '20051915'
 '21053047']


In [68]:
print(roll_numbers)

['Roll' '2005011' '2005058' '2005076' '2005119' '2005150' '2005161'
 '2005168' '2005178' '2005179' '2005198' '2005270' '2005278' '2005288'
 '2005289' '2005312' '2005324' '2005326' '2005332' '2005343' '2005407'
 '2005439' '2005444' '2005473' '2005521' '2005548' '2005554' '2005574'
 '2005578' '2005585' '2005590' '2005597' '2005598' '2005601' '2005603'
 '2005608' '2005628' '2005631' '2005645' '2005704' '2005718' '2005721'
 '2005849' '2005904' '2005909' '2005929' '2005955' '2005979' '20051001'
 '20051023' '20051042' '20051049' '20051105' '20051122' '20051143'
 '20051164' '20051167' '20051174' '20051182' '20051254' '20051329'
 '20051351' '20051359' '20051362' '20051388' '20051397' '20051420'
 '20051433' '20051467' '20051473' '20051510' '20051552' '20051562'
 '20051614' '20051633' '20051805' '20051855' '20051866' '20051868'
 '20051872' '20051888' '20051903' '20051915' '20051962' '20051981'
 '21053002' '21053015' '21053022' '21053042' '21053047' '21053066'
 '21053067']


In [74]:
intervals = [2,4,6,10]

for i in range(len(intervals) - 1):
    start = intervals[i]
    end = intervals[i + 1]
    print("Roll numbers in interval", f"[{start}, {end}):")
    print(roll_numbers[start:end])
    print()

Roll numbers in interval [2, 4):
['2005058' '2005076']

Roll numbers in interval [4, 6):
['2005119' '2005150']

Roll numbers in interval [6, 10):
['2005161' '2005168' '2005178' '2005179']



In [75]:
max_mark_index = np.argmax(marks)
max_serial_number = serial_numbers[max_mark_index]
max_roll_number = roll_numbers[max_mark_index]
print("Student with maximum marks:")
print("Serial number:", max_serial_number)
print("Roll number:", max_roll_number)

Student with maximum marks:
Serial number: Score
Roll number: Roll


In [51]:
arange_array = np.arange(10)

arange_array_step = np.arange(2, 11, 2)

print("Arange array:")
print(arange_array)
print("\nArange array with step:")
print(arange_array_step)

Arange array:
[0 1 2 3 4 5 6 7 8 9]

Arange array with step:
[ 2  4  6  8 10]
